/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ReceiptsReceiptIdRouteImport } from './routes/receipts/$receiptId'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles/$articleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdRoute = ReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/receipts': typeof ReceiptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/receipts': typeof ReceiptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/$articleId'
    | '/receipts/$receiptId'
    | '/articles'
    | '/receipts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/$articleId'
    | '/receipts/$receiptId'
    | '/articles'
    | '/receipts'
  id:
    | '__root__'
    | '/'
    | '/articles/$articleId'
    | '/receipts/$receiptId'
    | '/articles/'
    | '/receipts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  ReceiptsReceiptIdRoute: typeof ReceiptsReceiptIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$receiptId': {
      id: '/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof ReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  ReceiptsReceiptIdRoute: ReceiptsReceiptIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
