/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptsReceiptIdRouteImport } from './routes/receipts_/$receiptId'

const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdRoute = ReceiptsReceiptIdRouteImport.update({
  id: '/receipts_/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/receipts': typeof ReceiptsRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/receipts': typeof ReceiptsRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/receipts': typeof ReceiptsRoute
  '/receipts_/$receiptId': typeof ReceiptsReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/receipts' | '/receipts/$receiptId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/receipts' | '/receipts/$receiptId'
  id: '__root__' | '/' | '/receipts' | '/receipts_/$receiptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ReceiptsReceiptIdRoute: typeof ReceiptsReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts_/$receiptId': {
      id: '/receipts_/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof ReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReceiptsRoute: ReceiptsRoute,
  ReceiptsReceiptIdRoute: ReceiptsReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
