/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ArticlePurchaseQuantity } from "./articlePurchaseQuantity";
import type { ArticlePurchasePrice } from "./articlePurchasePrice";

export interface ArticlePurchase {
  receiptId: string;
  timeStamp: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  quantity: ArticlePurchaseQuantity;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  price: ArticlePurchasePrice;
}
