/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleId } from "./articleId";
import type { ReceiptArticle } from "./receiptArticle";

export interface Article {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: ArticleId;
  productName: string;
  imageUrl: string;
  receipts: ReceiptArticle[];
}
