/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1ArticleParams = {
  /**
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  offset?: number | string;
  /**
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  perPage?: number | string;
  query?: string;
};
