/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GetResponseReceiptsCount } from "./getResponseReceiptsCount";
import type { GetResponseArticlesCount } from "./getResponseArticlesCount";
import type { GetResponseLastError } from "./getResponseLastError";

export interface GetResponse {
  isFetching: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  receiptsCount: GetResponseReceiptsCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  articlesCount: GetResponseArticlesCount;
  lastError: GetResponseLastError;
}
