/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MarketId } from "./marketId";

export interface Market {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: MarketId;
  name?: string;
  street?: string;
  zipCode?: string;
  city?: string;
}
