/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ReceiptArticleNan } from "./receiptArticleNan";
import type { ReceiptArticleQuantity } from "./receiptArticleQuantity";
import type { ReceiptArticlePrice } from "./receiptArticlePrice";

export interface ReceiptArticle {
  id: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  nan: ReceiptArticleNan;
  productName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  quantity: ReceiptArticleQuantity;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  price: ReceiptArticlePrice;
}
