/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ReceiptLineQuantity } from "./receiptLineQuantity";
import type { ReceiptLinePrice } from "./receiptLinePrice";

export interface ReceiptLine {
  id: string;
  productName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  quantity: ReceiptLineQuantity;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  price: ReceiptLinePrice;
}
