/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Market } from "./market";
import type { ReceiptBriefTotal } from "./receiptBriefTotal";

export interface ReceiptBrief {
  id: string;
  market: Market;
  date: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  total: ReceiptBriefTotal;
}
