/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Market } from "./market";
import type { ReceiptFullTotal } from "./receiptFullTotal";
import type { ReceiptLine } from "./receiptLine";

export interface ReceiptFull {
  id: string;
  market: Market;
  date: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  total: ReceiptFullTotal;
  paybackFlag: boolean;
  cancelled: boolean;
  lines: ReceiptLine[];
}
