/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
 */
export type ReceiptBriefTotal = number | string;
