/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetResponse, PostApiV1FetchParams } from "../schemas";

import { customFetch } from "../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getApiV1FetchResponse200 = {
  data: GetResponse;
  status: 200;
};

export type getApiV1FetchResponseSuccess = getApiV1FetchResponse200 & {
  headers: Headers;
};
export type getApiV1FetchResponse = getApiV1FetchResponseSuccess;

export const getGetApiV1FetchUrl = () => {
  return `/api/v1/Fetch`;
};

export const getApiV1Fetch = async (
  options?: RequestInit,
): Promise<getApiV1FetchResponse> => {
  return customFetch<getApiV1FetchResponse>(getGetApiV1FetchUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetApiV1FetchQueryKey = () => {
  return [`/api/v1/Fetch`] as const;
};

export const getGetApiV1FetchQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Fetch>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiV1Fetch>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1FetchQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Fetch>>> = ({
    signal,
  }) => getApiV1Fetch({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Fetch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1FetchQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Fetch>>
>;
export type GetApiV1FetchQueryError = unknown;

export function useGetApiV1Fetch<
  TData = Awaited<ReturnType<typeof getApiV1Fetch>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Fetch>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Fetch>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Fetch>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Fetch<
  TData = Awaited<ReturnType<typeof getApiV1Fetch>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Fetch>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Fetch>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Fetch>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Fetch<
  TData = Awaited<ReturnType<typeof getApiV1Fetch>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Fetch>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiV1Fetch<
  TData = Awaited<ReturnType<typeof getApiV1Fetch>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Fetch>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiV1FetchQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type postApiV1FetchResponse200 = {
  data: void;
  status: 200;
};

export type postApiV1FetchResponseSuccess = postApiV1FetchResponse200 & {
  headers: Headers;
};
export type postApiV1FetchResponse = postApiV1FetchResponseSuccess;

export const getPostApiV1FetchUrl = (params?: PostApiV1FetchParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/Fetch?${stringifiedParams}`
    : `/api/v1/Fetch`;
};

export const postApiV1Fetch = async (
  params?: PostApiV1FetchParams,
  options?: RequestInit,
): Promise<postApiV1FetchResponse> => {
  return customFetch<postApiV1FetchResponse>(getPostApiV1FetchUrl(params), {
    ...options,
    method: "POST",
  });
};

export const getPostApiV1FetchMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1Fetch>>,
    TError,
    { params?: PostApiV1FetchParams },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1Fetch>>,
  TError,
  { params?: PostApiV1FetchParams },
  TContext
> => {
  const mutationKey = ["postApiV1Fetch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1Fetch>>,
    { params?: PostApiV1FetchParams }
  > = (props) => {
    const { params } = props ?? {};

    return postApiV1Fetch(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1FetchMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1Fetch>>
>;

export type PostApiV1FetchMutationError = unknown;

export const usePostApiV1Fetch = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1Fetch>>,
      TError,
      { params?: PostApiV1FetchParams },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1Fetch>>,
  TError,
  { params?: PostApiV1FetchParams },
  TContext
> => {
  const mutationOptions = getPostApiV1FetchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
