/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { Post, PostApiV1PostParams } from "../schemas";

import { customFetch } from "../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getApiV1PostResponse200 = {
  data: Post[];
  status: 200;
};

export type getApiV1PostResponseSuccess = getApiV1PostResponse200 & {
  headers: Headers;
};
export type getApiV1PostResponse = getApiV1PostResponseSuccess;

export const getGetApiV1PostUrl = () => {
  return `/api/v1/Post`;
};

export const getApiV1Post = async (
  options?: RequestInit,
): Promise<getApiV1PostResponse> => {
  return customFetch<getApiV1PostResponse>(getGetApiV1PostUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetApiV1PostQueryKey = () => {
  return [`/api/v1/Post`] as const;
};

export const getGetApiV1PostQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Post>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiV1Post>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1PostQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Post>>> = ({
    signal,
  }) => getApiV1Post({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Post>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1PostQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Post>>
>;
export type GetApiV1PostQueryError = unknown;

export function useGetApiV1Post<
  TData = Awaited<ReturnType<typeof getApiV1Post>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Post>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Post>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Post>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Post<
  TData = Awaited<ReturnType<typeof getApiV1Post>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Post>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Post>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Post>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Post<
  TData = Awaited<ReturnType<typeof getApiV1Post>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Post>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiV1Post<
  TData = Awaited<ReturnType<typeof getApiV1Post>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiV1Post>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiV1PostQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type postApiV1PostResponse200 = {
  data: Post;
  status: 200;
};

export type postApiV1PostResponseSuccess = postApiV1PostResponse200 & {
  headers: Headers;
};
export type postApiV1PostResponse = postApiV1PostResponseSuccess;

export const getPostApiV1PostUrl = (params?: PostApiV1PostParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/Post?${stringifiedParams}`
    : `/api/v1/Post`;
};

export const postApiV1Post = async (
  params?: PostApiV1PostParams,
  options?: RequestInit,
): Promise<postApiV1PostResponse> => {
  return customFetch<postApiV1PostResponse>(getPostApiV1PostUrl(params), {
    ...options,
    method: "POST",
  });
};

export const getPostApiV1PostMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1Post>>,
    TError,
    { params?: PostApiV1PostParams },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1Post>>,
  TError,
  { params?: PostApiV1PostParams },
  TContext
> => {
  const mutationKey = ["postApiV1Post"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1Post>>,
    { params?: PostApiV1PostParams }
  > = (props) => {
    const { params } = props ?? {};

    return postApiV1Post(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1PostMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1Post>>
>;

export type PostApiV1PostMutationError = unknown;

export const usePostApiV1Post = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1Post>>,
      TError,
      { params?: PostApiV1PostParams },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1Post>>,
  TError,
  { params?: PostApiV1PostParams },
  TContext
> => {
  const mutationOptions = getPostApiV1PostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type deleteApiV1PostIdResponse200 = {
  data: void;
  status: 200;
};

export type deleteApiV1PostIdResponseSuccess = deleteApiV1PostIdResponse200 & {
  headers: Headers;
};
export type deleteApiV1PostIdResponse = deleteApiV1PostIdResponseSuccess;

export const getDeleteApiV1PostIdUrl = (id: string) => {
  return `/api/v1/Post/${id}`;
};

export const deleteApiV1PostId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteApiV1PostIdResponse> => {
  return customFetch<deleteApiV1PostIdResponse>(getDeleteApiV1PostIdUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteApiV1PostIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiV1PostId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiV1PostId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiV1PostId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiV1PostId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiV1PostId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1PostIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiV1PostId>>
>;

export type DeleteApiV1PostIdMutationError = unknown;

export const useDeleteApiV1PostId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiV1PostId>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiV1PostId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiV1PostIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
