/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * ReweReceipt.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetApiV1ReceiptParams,
  ReceiptBrief,
  ReceiptFull,
} from "../schemas";

import { customFetch } from "../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getApiV1ReceiptResponse200 = {
  data: ReceiptBrief[];
  status: 200;
};

export type getApiV1ReceiptResponseSuccess = getApiV1ReceiptResponse200 & {
  headers: Headers;
};
export type getApiV1ReceiptResponse = getApiV1ReceiptResponseSuccess;

export const getGetApiV1ReceiptUrl = (params?: GetApiV1ReceiptParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/Receipt?${stringifiedParams}`
    : `/api/v1/Receipt`;
};

export const getApiV1Receipt = async (
  params?: GetApiV1ReceiptParams,
  options?: RequestInit,
): Promise<getApiV1ReceiptResponse> => {
  return customFetch<getApiV1ReceiptResponse>(getGetApiV1ReceiptUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetApiV1ReceiptQueryKey = (params?: GetApiV1ReceiptParams) => {
  return [`/api/v1/Receipt`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1ReceiptQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Receipt>>,
  TError = unknown,
>(
  params?: GetApiV1ReceiptParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Receipt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1ReceiptQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Receipt>>> = ({
    signal,
  }) => getApiV1Receipt(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Receipt>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1ReceiptQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Receipt>>
>;
export type GetApiV1ReceiptQueryError = unknown;

export function useGetApiV1Receipt<
  TData = Awaited<ReturnType<typeof getApiV1Receipt>>,
  TError = unknown,
>(
  params: undefined | GetApiV1ReceiptParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Receipt>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Receipt>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Receipt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Receipt<
  TData = Awaited<ReturnType<typeof getApiV1Receipt>>,
  TError = unknown,
>(
  params?: GetApiV1ReceiptParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Receipt>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Receipt>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Receipt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Receipt<
  TData = Awaited<ReturnType<typeof getApiV1Receipt>>,
  TError = unknown,
>(
  params?: GetApiV1ReceiptParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Receipt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiV1Receipt<
  TData = Awaited<ReturnType<typeof getApiV1Receipt>>,
  TError = unknown,
>(
  params?: GetApiV1ReceiptParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Receipt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiV1ReceiptQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type getApiV1ReceiptIdResponse200 = {
  data: ReceiptFull;
  status: 200;
};

export type getApiV1ReceiptIdResponseSuccess = getApiV1ReceiptIdResponse200 & {
  headers: Headers;
};
export type getApiV1ReceiptIdResponse = getApiV1ReceiptIdResponseSuccess;

export const getGetApiV1ReceiptIdUrl = (id: string) => {
  return `/api/v1/Receipt/${id}`;
};

export const getApiV1ReceiptId = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1ReceiptIdResponse> => {
  return customFetch<getApiV1ReceiptIdResponse>(getGetApiV1ReceiptIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetApiV1ReceiptIdQueryKey = (id?: string) => {
  return [`/api/v1/Receipt/${id}`] as const;
};

export const getGetApiV1ReceiptIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1ReceiptId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1ReceiptId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1ReceiptIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1ReceiptId>>
  > = ({ signal }) => getApiV1ReceiptId(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1ReceiptId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1ReceiptIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1ReceiptId>>
>;
export type GetApiV1ReceiptIdQueryError = unknown;

export function useGetApiV1ReceiptId<
  TData = Awaited<ReturnType<typeof getApiV1ReceiptId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1ReceiptId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ReceiptId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ReceiptId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1ReceiptId<
  TData = Awaited<ReturnType<typeof getApiV1ReceiptId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1ReceiptId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ReceiptId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ReceiptId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1ReceiptId<
  TData = Awaited<ReturnType<typeof getApiV1ReceiptId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1ReceiptId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiV1ReceiptId<
  TData = Awaited<ReturnType<typeof getApiV1ReceiptId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1ReceiptId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiV1ReceiptIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
